# Puerto del servidor
server.port=8080

# H2 Database (en memoria)
spring.datasource.url=jdbc:h2:mem:techconfdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate crea la tabla y luego se ejecuta data.sql
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
# Necesario para que data.sql corra DESPUES de que Hibernate cree la tabla "charla"
spring.jpa.defer-datasource-initialization=true
